import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://www.cusiflores.com'

  return [
    {
      url: `${baseUrl}/`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'weekly',
      priority: 1,
    },
    {
      url: `${baseUrl}/quienes-somos`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/flores-lomas-de-chapultepec`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${baseUrl}/flores-bosques-de-las-lomas`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${baseUrl}/flores-polanco`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${baseUrl}/flores-santa-fe`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${baseUrl}/flores-a-domicilio-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/arreglos-florales-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/ramos-de-flores-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${baseUrl}/orquideas-a-domicilio-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${baseUrl}/flores-para-cumpleanos-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${baseUrl}/flores-dia-de-las-madres-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${baseUrl}/aviso-de-privacidad`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${baseUrl}/condiciones-generales-de-uso`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${baseUrl}/pago-de-impuestos`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${baseUrl}/en`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/en/flowers-lomas-de-chapultepec`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/en/flowers-bosques-de-las-lomas`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/en/flower-delivery-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/en/floral-arrangements-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/en/flower-bouquets-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/en/orchid-delivery-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/en/birthday-flowers-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/en/mothers-day-flowers-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/en/about`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/en/privacy-policy`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${baseUrl}/en/terms-of-use`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${baseUrl}/en/tax-information`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'yearly',
      priority: 0.3,
     },
    {
      url: `${baseUrl}/it`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/it/fiori-lomas-de-chapultepec`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/it/fiori-bosques-de-las-lomas`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/it/consegna-fiori-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/it/composizioni-floreali-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/it/bouquet-fiori-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/it/consegna-orchidee-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/it/fiori-compleanno-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/it/fiori-festa-della-mamma-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/it/about`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/it/privacy-policy`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${baseUrl}/it/terms-of-use`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${baseUrl}/it/tax-information`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${baseUrl}/fr`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/fr/fleurs-lomas-de-chapultepec`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/fr/fleurs-bosques-de-las-lomas`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/fr/livraison-fleurs-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/fr/compositions-florales-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/fr/bouquets-fleurs-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/fr/livraison-orchidees-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/fr/fleurs-anniversaire-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/fr/fleurs-fete-des-meres-cdmx`,
      lastModified: new Date('2026-05-23'),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: `${baseUrl}/fr/about`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/fr/privacy-policy`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${baseUrl}/fr/terms-of-use`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${baseUrl}/fr/tax-information`,
      lastModified: new Date('2026-05-07'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
  ]
}
